/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hinnoitteluohjelmisto;

import javax.swing.DefaultListModel;

/**
 *
 * @author 20128509
 */
public class Hinnoitteluohjelmisto extends javax.swing.JFrame {

    /**
     * Creates new form Hinnoitteluohjelmisto
     */
    public Hinnoitteluohjelmisto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jradioAikuiset = new javax.swing.JRadioButton();
        jchkRaidat = new javax.swing.JCheckBox();
        jbtnTilaa = new javax.swing.JButton();
        jtxtAlennus = new javax.swing.JTextField();
        jradioLapset = new javax.swing.JRadioButton();
        jradioLyhyet = new javax.swing.JRadioButton();
        jradioKeskipitkät = new javax.swing.JRadioButton();
        jradioPitkät = new javax.swing.JRadioButton();
        jchkTyviväri = new javax.swing.JCheckBox();
        jchkVärjäys = new javax.swing.JCheckBox();
        jchkJuhlakampaus = new javax.swing.JCheckBox();
        jchkKoekampaus = new javax.swing.JCheckBox();
        jchkPesu = new javax.swing.JCheckBox();
        jchkKiharrus = new javax.swing.JCheckBox();
        jchkPermanentti = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListTilaus = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtHenkilömäärä = new javax.swing.JTextField();
        jtxtHinta = new javax.swing.JTextField();
        jtxtHintaYhteensä = new javax.swing.JTextField();
        jbtnPoista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("<- GET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ADD ->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jList1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "aikuiset 25 eur", "lapset 15 eur", "lyhyet 0 eur ", "keskipitkät 5 eur", "pitkät 10 eur", "raidat 30 eur", "tyviväri 30 eur", "hiusten värjäys 80 eur", "juhlakampaus 50 eur", "koekampaus 20 eur", "pesu 10 eur", "kiharrus 15 eur", "permanentti 50 eur", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(jList2);

        buttonGroup1.add(jradioAikuiset);
        jradioAikuiset.setText("aikuiset 25€");

        jchkRaidat.setText("raidat 30€");

        jbtnTilaa.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jbtnTilaa.setText("Tilaa");
        jbtnTilaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTilaaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jradioLapset);
        jradioLapset.setText("lapset 15€");

        buttonGroup2.add(jradioLyhyet);
        jradioLyhyet.setText("lyhyet 0€");

        buttonGroup2.add(jradioKeskipitkät);
        jradioKeskipitkät.setText("keskipitkät 5€");

        buttonGroup2.add(jradioPitkät);
        jradioPitkät.setText("pitkät 10€");

        jchkTyviväri.setText("tyviväri 30€");

        jchkVärjäys.setText("hiusten värjäys 80€");

        jchkJuhlakampaus.setText("juhlakampaus 50€");

        jchkKoekampaus.setText("koekampaus 20€");

        jchkPesu.setText("pesu 10€");

        jchkKiharrus.setText("kiharrus 15€");

        jchkPermanentti.setText("permanentti 50€");

        jLabel1.setText("Alennus");

        jScrollPane3.setViewportView(jListTilaus);

        jLabel2.setText("Henkilömäärä");

        jLabel3.setText("Hinta");

        jLabel4.setText("Hinta yhteensä");

        jbtnPoista.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jbtnPoista.setText("Poista");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jradioLyhyet, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkKoekampaus, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkPermanentti, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkKiharrus, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkPesu, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jradioAikuiset, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jradioLapset, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jradioKeskipitkät, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkTyviväri, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkJuhlakampaus, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jradioPitkät, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkRaidat, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkVärjäys, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)))
                                    .addComponent(jbtnTilaa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtAlennus, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtxtHintaYhteensä, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtxtHinta, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtxtHenkilömäärä, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnPoista, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jradioAikuiset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jradioLapset)
                .addGap(18, 18, 18)
                .addComponent(jradioLyhyet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jradioKeskipitkät)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jradioPitkät)
                .addGap(18, 18, 18)
                .addComponent(jchkRaidat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkTyviväri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkVärjäys)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkJuhlakampaus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkKoekampaus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkPesu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkKiharrus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkPermanentti)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtAlennus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtHenkilömäärä, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtHinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addComponent(jtxtHintaYhteensä, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jbtnTilaa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPoista))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /* DefaultListModel dlm = new DefaultListModel();
        for (int i = 0; i < 10; i++) {
            dlm.addElement("item: " + i);
        }
        jList1.setModel(dlm);
         */
    }//GEN-LAST:event_jButton1ActionPerformed
    DefaultListModel dlm = new DefaultListModel();

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /*  dlm2.addElement(jList1.getSelectedValue());
        jList2.setModel(dlm2);*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtnTilaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTilaaActionPerformed
        jradioAikuiset.setActionCommand("Aikuiset");
        jradioLapset.setActionCommand("Lapset");
        jradioLyhyet.setActionCommand("Lyhyet");
        jradioKeskipitkät.setActionCommand("Keskipitkät");
        jradioPitkät.setActionCommand("Pitkät");

        double hinta = 0;

        if (buttonGroup1.getSelection().getActionCommand() == "Aikuiset") {
            hinta = 25;
        } else if (buttonGroup1.getSelection().getActionCommand() == "Lapset") {
            hinta = 15;
        }

        if (buttonGroup2.getSelection().getActionCommand() == "Lyhyet") {
            hinta = hinta + 0;
        } else if (buttonGroup2.getSelection().getActionCommand() == "Keskipitkät") {
            hinta = hinta + 5;
        } else if (buttonGroup2.getSelection().getActionCommand() == "Pitkät") {
            hinta = hinta + 10;
        }

        if (jchkRaidat.isSelected()) {
            hinta = hinta + 30;
        }
        if (jchkTyviväri.isSelected()) {
            hinta = hinta + 30;
        }
        if (jchkVärjäys.isSelected()) {
            hinta = hinta + 80;
        }
        if (jchkJuhlakampaus.isSelected()) {
            hinta = hinta + 50;
        }
        if (jchkKoekampaus.isSelected()) {
            hinta = hinta + 20;
        }
        if (jchkPesu.isSelected()) {
            hinta = hinta + 10;
        }
        if (jchkKiharrus.isSelected()) {
            hinta = hinta + 15;
        }
        if (jchkPermanentti.isSelected()) {
            hinta = hinta + 50;
        }

        jtxtHinta.setText(String.valueOf(hinta));

        //Internet-varauksella saa - 5 eur alennuksen, jos kokonaissumma on 25 eur tai enemmän.
        int maara = Integer.parseInt(jtxtHenkilömäärä.getText());
        double yhteensa, alennus;
        yhteensa = maara * hinta;

        //jos se on toinen vaihtoehto , ei lasketa 5% MIKSI?
        if (yhteensa < 25) {
            alennus = 0;
            jtxtAlennus.setText("0");
        } else {
            try {
                alennus = Double.parseDouble(jtxtAlennus.getText());

            } catch (Exception e) {
                alennus = 5;
                jtxtAlennus.setText("5");
                yhteensa = hinta - hinta * 5.0 / 100;
            }
        }

        jtxtHintaYhteensä.setText(String.valueOf(yhteensa));

        // lisää List-objektiin yhteissumman (henkilömäärä, hinta sekä henkilömäärä x hinta)
        

        dlm.addElement("henkilömäärä: " + maara + " kpl    " + "hinta: " + hinta + " €    " + "yhteensä: " + yhteensa + " €    " );

        jListTilaus.setModel(dlm);


    }//GEN-LAST:event_jbtnTilaaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hinnoitteluohjelmisto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hinnoitteluohjelmisto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hinnoitteluohjelmisto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hinnoitteluohjelmisto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hinnoitteluohjelmisto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jListTilaus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtnPoista;
    private javax.swing.JButton jbtnTilaa;
    private javax.swing.JCheckBox jchkJuhlakampaus;
    private javax.swing.JCheckBox jchkKiharrus;
    private javax.swing.JCheckBox jchkKoekampaus;
    private javax.swing.JCheckBox jchkPermanentti;
    private javax.swing.JCheckBox jchkPesu;
    private javax.swing.JCheckBox jchkRaidat;
    private javax.swing.JCheckBox jchkTyviväri;
    private javax.swing.JCheckBox jchkVärjäys;
    private javax.swing.JRadioButton jradioAikuiset;
    private javax.swing.JRadioButton jradioKeskipitkät;
    private javax.swing.JRadioButton jradioLapset;
    private javax.swing.JRadioButton jradioLyhyet;
    private javax.swing.JRadioButton jradioPitkät;
    private javax.swing.JTextField jtxtAlennus;
    private javax.swing.JTextField jtxtHenkilömäärä;
    private javax.swing.JTextField jtxtHinta;
    private javax.swing.JTextField jtxtHintaYhteensä;
    // End of variables declaration//GEN-END:variables
}
