/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hinnoitteluohjelmisto;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author 20128509
 */
public class Hinnoitteluohjelmisto extends javax.swing.JFrame {

    int henkilo;
    int yhteensa;
    double alennus;
    double yhteenveto;

    /**
     * Creates new form Hinnoitteluohjelmisto
     */
    public Hinnoitteluohjelmisto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jradioAikuiset = new javax.swing.JRadioButton();
        jchkRaidat = new javax.swing.JCheckBox();
        jbtnTilaa = new javax.swing.JButton();
        jtxtAlennus = new javax.swing.JTextField();
        jradioLapset = new javax.swing.JRadioButton();
        jradioLyhyet = new javax.swing.JRadioButton();
        jradioKeskipitkät = new javax.swing.JRadioButton();
        jradioPitkät = new javax.swing.JRadioButton();
        jchkTyviväri = new javax.swing.JCheckBox();
        jchkVärjäys = new javax.swing.JCheckBox();
        jchkJuhlakampaus = new javax.swing.JCheckBox();
        jchkKoekampaus = new javax.swing.JCheckBox();
        jchkPesu = new javax.swing.JCheckBox();
        jchkKiharrus = new javax.swing.JCheckBox();
        jchkPermanentti = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtHenkilömäärä = new javax.swing.JTextField();
        jtxtYhteensä = new javax.swing.JTextField();
        jtxtYhteenveto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("<- GET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ADD ->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jList2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(jList2);

        buttonGroup1.add(jradioAikuiset);
        jradioAikuiset.setText("aikuiset 25€");

        jchkRaidat.setText("raidat 30€");

        jbtnTilaa.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jbtnTilaa.setText("Tilaa");
        jbtnTilaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTilaaActionPerformed(evt);
            }
        });

        jtxtAlennus.setEditable(false);

        buttonGroup1.add(jradioLapset);
        jradioLapset.setText("lapset 15€");

        buttonGroup2.add(jradioLyhyet);
        jradioLyhyet.setText("lyhyet 0€");

        buttonGroup2.add(jradioKeskipitkät);
        jradioKeskipitkät.setText("keskipitkät 5€");

        buttonGroup2.add(jradioPitkät);
        jradioPitkät.setText("pitkät 10€");

        jchkTyviväri.setText("tyviväri 30€");

        jchkVärjäys.setText("hiusten värjäys 80€");

        jchkJuhlakampaus.setText("juhlakampaus 50€");

        jchkKoekampaus.setText("koekampaus 20€");

        jchkPesu.setText("pesu 10€");

        jchkKiharrus.setText("kiharrus 15€");

        jchkPermanentti.setText("permanentti 50€");

        jLabel1.setText("Alennus (5 €):");

        jLabel2.setText("Henkilömäärä* :");

        jLabel4.setText("Hinta");

        jtxtYhteensä.setEditable(false);

        jtxtYhteenveto.setEditable(false);

        jLabel5.setText("Yhteenveto: ");

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jList1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "aikuiset 25 eur", "lapset 15 eur", "lyhyet 0 eur ", "keskipitkät 5 eur", "pitkät 10 eur", "raidat 30 eur", "tyviväri 30 eur", "hiusten värjäys 80 eur", "juhlakampaus 50 eur", "koekampaus 20 eur", "pesu 10 eur", "kiharrus 15 eur", "permanentti 50 eur" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchkKoekampaus)
                            .addComponent(jchkPermanentti)
                            .addComponent(jchkKiharrus)
                            .addComponent(jchkPesu)
                            .addComponent(jradioAikuiset)
                            .addComponent(jchkTyviväri)
                            .addComponent(jchkJuhlakampaus)
                            .addComponent(jradioPitkät)
                            .addComponent(jchkRaidat)
                            .addComponent(jchkVärjäys)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jradioKeskipitkät)
                                    .addComponent(jradioLyhyet)
                                    .addComponent(jradioLapset))
                                .addGap(28, 28, 28)))
                        .addGap(49, 49, 49)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtHenkilömäärä, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtYhteenveto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtYhteensä, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtAlennus, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jbtnTilaa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtHenkilömäärä, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jradioAikuiset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jradioLapset)
                                .addGap(20, 20, 20)
                                .addComponent(jradioLyhyet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jradioKeskipitkät)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jradioPitkät)
                                .addGap(28, 28, 28)
                                .addComponent(jchkRaidat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jchkTyviväri)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jchkVärjäys)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jchkJuhlakampaus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jchkKoekampaus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jchkPesu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jchkKiharrus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jchkPermanentti))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel4))
                                    .addComponent(jtxtYhteensä, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jtxtAlennus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxtYhteenveto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnTilaa)
                                .addGap(80, 80, 80)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /* DefaultListModel dlm = new DefaultListModel();
        for (int i = 0; i < 10; i++) {
            dlm.addElement("item: " + i);
        }
        jList1.setModel(dlm);
         */
        dlm2.removeElement(jList2.getSelectedValue());
        jList2.setModel(dlm2);

    }//GEN-LAST:event_jButton1ActionPerformed
    DefaultListModel dlm2 = new DefaultListModel();

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dlm2.addElement(jList1.getSelectedValue());
        jList2.setModel(dlm2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtnTilaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTilaaActionPerformed

        dlm2.addElement("-----------------------------");
        dlm2.addElement("Henkilomäärä: " + henkilo);
        dlm2.addElement("Yhteensa: " + yhteensa + " €");
        dlm2.addElement("Alennus: " + alennus + " €");
        dlm2.addElement("Laskun summa: " + yhteenveto + " €");
        dlm2.addElement("-----------------------------");
        dlm2.addElement("KIITOS KÄYNNISTÄ!");
        jList2.setModel(dlm2);

    }//GEN-LAST:event_jbtnTilaaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        //henkilomaara
        try {
            if (jtxtHenkilömäärä.getText().isBlank()) {
                JOptionPane.showMessageDialog(null, "Kirjoita henkilomäärä ", "VIRHE", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Integer.valueOf(jtxtHenkilömäärä.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Vain lukuja, kiitos. Virhe: " + e.getMessage(), "VIRHE", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //add 
        if (jradioAikuiset.isSelected()) {
            jList1.getSelectedValue();
            dlm2.addElement(jList1.getModel().getElementAt(0));
            jList2.setModel(dlm2);
        } else if (jradioLapset.isSelected()) {
            jList1.getSelectedValue();
            dlm2.addElement(jList1.getModel().getElementAt(1));
            jList2.setModel(dlm2);
        }
        buttonGroup1.clearSelection();

        if (jradioLyhyet.isSelected()) {
            jList1.getSelectedValue();
            dlm2.addElement(jList1.getModel().getElementAt(2));
            jList2.setModel(dlm2);
        } else if (jradioKeskipitkät.isSelected()) {
            jList1.getSelectedValue();
            dlm2.addElement(jList1.getModel().getElementAt(3));
            jList2.setModel(dlm2);
        } else if (jradioPitkät.isSelected()) {
            jList1.getSelectedValue();
            dlm2.addElement(jList1.getModel().getElementAt(4));
            jList2.setModel(dlm2);
        }
        buttonGroup2.clearSelection();

        if (jchkRaidat.isSelected()) {
            jList1.getSelectedValue();
            dlm2.addElement(jList1.getModel().getElementAt(5));
            jList2.setModel(dlm2);
        }
        jchkRaidat.setSelected(false);

        if (jchkTyviväri.isSelected()) {
            jList1.getSelectedValue();
            dlm2.addElement(jList1.getModel().getElementAt(6));
            jList2.setModel(dlm2);
        }
        jchkTyviväri.setSelected(false);

        if (jchkVärjäys.isSelected()) {
            jList1.getSelectedValue();
            dlm2.addElement(jList1.getModel().getElementAt(7));
            jList2.setModel(dlm2);
        }
        jchkVärjäys.setSelected(false);

        if (jchkJuhlakampaus.isSelected()) {
            jList1.getSelectedValue();
            dlm2.addElement(jList1.getModel().getElementAt(8));
            jList2.setModel(dlm2);
        }
        jchkJuhlakampaus.setSelected(false);

        if (jchkKoekampaus.isSelected()) {
            jList1.getSelectedValue();
            dlm2.addElement(jList1.getModel().getElementAt(9));
            jList2.setModel(dlm2);
        }
        jchkKoekampaus.setSelected(false);

        if (jchkPesu.isSelected()) {
            jList1.getSelectedValue();
            dlm2.addElement(jList1.getModel().getElementAt(10));
            jList2.setModel(dlm2);
        }
        jchkPesu.setSelected(false);

        if (jchkKiharrus.isSelected()) {
            jList1.getSelectedValue();
            dlm2.addElement(jList1.getModel().getElementAt(11));
            jList2.setModel(dlm2);
        }
        jchkKiharrus.setSelected(false);

        if (jchkPermanentti.isSelected()) {
            jList1.getSelectedValue();
            dlm2.addElement(jList1.getModel().getElementAt(12));
            jList2.setModel(dlm2);
        }
        jchkPermanentti.setSelected(false);

        //summan laskeminen
        int summa = 0;
        yhteensa = 0;

        String a = dlm2.toString();
        System.out.println(a);
        String[] palat = a.split(", ");
        for (String rivi : palat) {
            String[] osaRivista = rivi.split(" ");
            summa += Integer.valueOf(osaRivista[1]);
        }

        henkilo = Integer.valueOf(jtxtHenkilömäärä.getText());

        yhteensa = summa * henkilo;

        jtxtYhteensä.setText(String.valueOf(yhteensa));

        alennus = 0;
        if (yhteensa >= 25) {
            alennus = 5;
            jtxtAlennus.setText(String.valueOf(alennus));
        }

        yhteenveto = yhteensa - alennus;
        jtxtYhteenveto.setText(String.valueOf(yhteenveto));
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hinnoitteluohjelmisto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hinnoitteluohjelmisto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hinnoitteluohjelmisto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hinnoitteluohjelmisto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hinnoitteluohjelmisto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnTilaa;
    private javax.swing.JCheckBox jchkJuhlakampaus;
    private javax.swing.JCheckBox jchkKiharrus;
    private javax.swing.JCheckBox jchkKoekampaus;
    private javax.swing.JCheckBox jchkPermanentti;
    private javax.swing.JCheckBox jchkPesu;
    private javax.swing.JCheckBox jchkRaidat;
    private javax.swing.JCheckBox jchkTyviväri;
    private javax.swing.JCheckBox jchkVärjäys;
    private javax.swing.JRadioButton jradioAikuiset;
    private javax.swing.JRadioButton jradioKeskipitkät;
    private javax.swing.JRadioButton jradioLapset;
    private javax.swing.JRadioButton jradioLyhyet;
    private javax.swing.JRadioButton jradioPitkät;
    private javax.swing.JTextField jtxtAlennus;
    private javax.swing.JTextField jtxtHenkilömäärä;
    private javax.swing.JTextField jtxtYhteensä;
    private javax.swing.JTextField jtxtYhteenveto;
    // End of variables declaration//GEN-END:variables
}
